openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - conversation

paths:
  /:
    post:
      tags: [conversation]
      summary: Set conversation marks
      description: |
        By calling this API, you can set or cancel marks for multiple conversations for multiple users. Each conversation can have up to 30 marks.

        The client will receive changes in conversation marks through the following ZIM SDK callback:

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|-------|---------|
        | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-group-member-info-updated-operated-info-group-id) | [onConversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~java_android~class~ZIMEventHandler#on-conversation-changed) | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-group-member-info-updated-operated-info-group-id) | [onConversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-conversation-changed) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |-----|--------|---------|--------------|
        | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#conversation-changed) | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#conversation-changed) | [onConversationChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onConversationChanged.html) | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#conversation-changed) |

        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|---------|
        | [OnConversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-conversation-changed) |[conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#group-application-updated) | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#conversation-changed) |  |  |

        <Note title="QPS Limit"> 20 times/s</Note>
      operationId: set-conversation-marks
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=SetConvMark
          required: true
          schema:
            type: string
            enum: [SetConvMark]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetConvMarkRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetConvMarkResponse'

components:
  schemas:
    SetConvMarkRequest:
      type: object
      required: [FromUserId, ConvMarkInfoList]
      properties:
        FromUserId:
          type: string
          description: |
            Operator user ID (who has logged in to the ZIM service by calling the login method on the client, or has completed registration by calling the [server-side API](/zim-server/user/batch-register-users)).

            > **Note**
            >
            > FromUserId only supports numbers, English characters, and "'!', '#', '$', '%', '&', '(', ')', '+', '', ':', ';', '<', '=', '.', '>', '?', '@', '[', ']', '^', '_', ' ', '{', '}', '|', '~'".
          maxLength: 32
          example: "user_test"
        ConvMarkInfoList:
          type: array
          description: Conversation mark objects, maximum 100 per request. An error will be reported if it exceeds 100 or is 0.
          maxItems: 100
          items:
            $ref: '#/components/schemas/StConvMarkInfo'
          example:
            - UserId: "userA"
              SetMarkC2c:
                conv_c2c_1:
                  MarkContent: 2
                conv_c2c_2:
                  MarkContent: 2
              SetMarkGroup:
                conv_group_1:
                  MarkContent: 2
                conv_group_2:
                  MarkContent: 2
              Action: true
            - UserId: "userB"
              SetMarkC2c:
                conv_c2c_1:
                  MarkContent: 2
                conv_c2c_2:
                  MarkContent: 2
              SetMarkGroup:
                conv_group_1:
                  MarkContent: 2
                conv_group_2:
                  MarkContent: 2
              Action: true
    StConvMarkInfo:
      type: object
      required: [UserId, Action]
      properties:
        UserId:
          type: string
          description: |
            Set or cancel conversation marks for this UserID.
            > **Note**
            >
            > When the target conversation is a group chat, this user must already be in the group chat.

            > **Note**
            >
            > UserId only supports numbers, English characters, and {"'!', '#', '$', '%', '&', '(', ')', '+', '-', ':', ';', '<', '=', '.', '>', '?', '@', '[', ']', '^', '_', ' ', '{', '}', '|', '~'}.
          example: "userA"
        SetMarkC2c:
          type: object
          description: |
            At least one of SetMarkC2c and SetMarkGroup must be selected.<br/>
            One-on-one conversation list (JSON Object). The key is the conversation ID, and the value is a JSON Object containing only the key MarkContent. The list can contain up to 100 conversations.
          additionalProperties:
            type: object
            required: [MarkContent]
            properties:
              MarkContent:
                type: number
                minimum: 1
                maximum: 30
                description: Conversation mark. An integer value in the range [1, 30].
                example: 2
          example:
            conv_c2c_1:
              MarkContent: 2
            conv_c2c_2:
              MarkContent: 2
        SetMarkGroup:
          type: object
          description: |
            At least one of SetMarkC2c and SetMarkGroup must be selected.<br/>
            Group conversation list (JSON Object). The key is the conversation ID, and the value is a JSON Object containing only the key MarkContent. The list can contain up to 100 conversations (group conversations must already exist and not be deleted).
          additionalProperties:
            type: object
            required: [MarkContent]
            properties:
              MarkContent:
                type: number
                minimum: 1
                maximum: 30
                description: Conversation mark. An integer value in the range [1, 30].
                example: 2
          example:
            conv_group_1:
              MarkContent: 2
            conv_group_2:
              MarkContent: 2
        Action:
          type: boolean
          description: |
            Mark operation:
            - true: Set mark.
            - false: Cancel mark.
          example: true
    SetConvMarkResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            > **Note**
            >
            > When you request to set or cancel marks for multiple conversations:
            > <ul><li>As long as the operation is successfully completed for at least one conversation, Code will return 0, indicating success. In this case, please refer to the specific information in FailList to understand the details of failed operations.</li>
            > <li>If the operations for all conversations fail, Code will return the relevant return code. For details, please refer to <a href="../return-codes.mdx">Return codes</a>.</li></ul>
            <table>
            <thead><tr><th>Return code</th><th>Description</th><th>Suggested Solution</th></tr></thead>
            <tbody>
            <tr><td>660000001</td><td>General business error.</td><td>Please retry or contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>660000002</td><td>Input parameter error.</td><td>Please check the input parameters.</td></tr>
            <tr><td>660300005</td><td>The API call frequency exceeds the AppID-level limit.</td><td>Please try again later.</td></tr>
            <tr><td>660800001</td><td>Error querying user information.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>660800054</td><td>Mark operations for all conversations failed.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        FailList:
          type: array
          description: |
            List of users for whom conversation mark operations failed.
            - When Code is 0:
              - If FailList is empty, conversation mark operations for all users succeeded.
              - If FailList is not empty, it means conversation mark operations for some users failed. Please refer to SubCode and SubMessage in FailList for handling.
            - When Code is not 0:
              - If FailList is empty, it indicates parameter error, API frequency limit, or system error.
              - If FailList is not empty, it means conversation mark operations for all users failed.
          items:
            $ref: '#/components/schemas/UserFailList'
          example:
            - SubCode: 0
              SubMessage: "succ"
              UserId: "UserA"
              FailList:
                - Code: 1
                  Message: "mark content is invalide"
                  ConvId: "conv_id_1"
                  ConvType: 0
                - Code: 1
                  Message: "mark content is invalide"
                  ConvId: "conv_id_2"
                  ConvType: 0
            - SubCode: 1
              SubMessage: "user not exist"
              UserId: "UserB"
    UserFailList:
      type: object
      properties:
        SubCode:
          type: number
          description: Used to identify the result of executing conversation mark operations for a user.
          example: 0
        SubMessage:
          type: string
          description: Describes the result of executing conversation mark operations for a user.
          example: "succ"
        UserId:
          type: string
          description: ID of the target user for the conversation mark operation.
          example: "UserA"
        FailList:
          type: array
          description: |
            List of target conversations for which mark operations failed.
            - When SubCode is 0:
              - If FailList is empty, operations for all target conversations of the target user succeeded.
              - If FailList is not empty, it means operations for some target conversations of the target user failed. Please refer to Code and Message in FailList for handling.
            - When SubCode is not 0:
              - If FailList is empty, it indicates parameter error, API frequency limit, or system error.
              - If FailList is not empty, it means operations for all target conversations of the target user failed.
          items:
            $ref: '#/components/schemas/ConvMarkFailList'
          example:
            - Code: 1
              Message: "mark content is invalide"
              ConvId: "conv_id_1"
              ConvType: 0
    ConvMarkFailList:
      type: object
      properties:
        Code:
          type: number
          description: Return code for failed operation.
          example: 1
        Message:
          type: string
          description: Description of failed operation.
          example: "mark content is invalide"
        ConvId:
          type: string
          description: |
            Conversation ID.
            - One-on-one conversation: Conversation ID is the user ID.
            - Group conversation: Conversation ID is the group ID.
          example: "conv_id_1"
        ConvType:
          type: number
          enum: [0, 2]
          description: |
            Conversation type.
            - 0: One-on-one conversation.
            - 2: Group conversation.
          example: 0
