openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: StartCDNRecord
      description: |
        CDN 可配置是否对所有直播流录制，若需要选择录制某条具体的直播流，可调用本接口实现。相关回调请参考 [录制文件生成回调](/real-time-video-server/callback/cdn/cdn-record-completed)。

        在使用腾讯云提供的 CDN 服务时，要明确以下录制参数：
        - 录制文件格式：支持 M3U8、FLV、MP4、AAC（单音频）和 MP3（单音频）。
        - 录制间隔：录制文件的时长，单位为秒 (s)，取值范围为 300 s ～ 7200 s，默认值为 7200 s。此参数对 M3U8 录制文件格式无效。如果希望录制文件的时长超过 7200 s（2 小时），则需要使用录制文件合并接口对多个录制文件进行合并。
        - 存储时长：明确录制文件的保留时长。

        <Warning title="注意">
        使用本接口之前需要明确录制参数，然后将录制参数同步给 ZEGO 技术支持进行配置，或前往 [ZEGO 控制台](https://console.zego.im) 自助配置，详情请参考 [控制台 - 服务配置 - CDN](/console/service-configuration/activate-cdn-service)。
        </Warning>
        <Note title="调用频率限制">同一个 AppID 下所有房间：20 次/秒</Note>
      operationId: start-cdn-recrod
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=StartCDNRecord
          required: true
          schema: { type: string, enum: [StartCDNRecord] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: StreamId
          in: query
          required: true
          description:
            流 ID 列表。<br />以同时录制 “cdn01” 和 “cdn02” 两个流为例，请求的参数为：StreamId[]=cdn01和StreamId[]=cdn02。
          schema:
            type: array
            items: { type: string }
            minItems: 1
          style: form
          explode: true
        - name: Vendor
          in: query
          required: true
          schema: { type: string, enum: [Tencent, Ws, Huawei, Aliyun] }
          description: |
            <p>CDN 厂商名。</p>
            Tencent：腾讯云。
            Ws：网宿。
            Huawei：华为云。
            Aliyun：阿里云。
        - name: EndTime
          in: query
          required: false
          description: |
            录制任务结束时间，Unix 时间戳。设置时间必须大于当前时间，且不能超过从当前时刻开始 24 小时之内的时间。

            <b>此参数仅在 Vendor 为 “Tencent” 时才生效。</b>
          schema: { type: string }
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartCDNRecordResponse'
              examples:
                Tencent:
                  summary: 腾讯云 响应示例（Vendor 为 Tencent 时返回）。
                  value:
                    Code: 0
                    Message: success
                    RequestId: 4315169065145771656
                    Data:
                      Tencent:
                        - StreamName: cdn01
                          TaskId: UUpTbkZUQV5WQVxrRFtDUQIUB29FWwMeAxwALBxMAggNHxw7WRUWGBVeEzoTDl0CDEoFNgIESVpXQV9rRVRCXlVKWGlFV0daVENeaFdURVNY
                          RequestId: 70628bcd-5652-4d5c-aa04-97956a4e771a
                          Code: ""
                          Message: ""
                Ws:
                  summary: 网宿 响应示例（Vendor 为 Ws 时返回）。
                  value:
                    Code: 0
                    Message: success
                    RequestId: 4315169065145771656
                    Data:
                      Ws:
                        msg: null
                        http_code: 200
                        trace_id: 15ccf21b-f3c2-4ee3-aaad-d995393f80cd
                        call_time: 2022-04-27 14:27:48
                        list:
                          - task: mp4
                            id: vega_test
                            http_code: 200
                            msg: success
                            persistentId: 2020bc8b648883c64e7e81f03cf72b70b86f
                Huawei:
                  summary: 华为云 响应示例（Vendor 为 Huawei 时返回）。
                  value:
                    Code: 0
                    Message: success
                    RequestId: 4315169065145771656
                    Data:
                      Huawei:
                        - StreamName: hwtest
                          RequestId: c373b2cc8a51159d4d60e0ec543csd88
                          Code: 0
                          Message: success
                Aliyun:
                  summary: 阿里云 响应示例（Vendor 为 Aliyun 时返回）。
                  value:
                    Code: 0
                    Message: success
                    RequestId: 16781707661
                    Data:
                      Aliyun:
                        - StreamName: clarechen_test
                          RequestId: AFC11DD6-9010-5235-9E44-E2DC24BCA148
                          Code: 200
                          Message: ""

components:
  schemas:
    StartCDNRecordResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。

            <table>
              <thead>
                <tr>
                  <th>返回码</th>
                  <th>说明</th>
                  <th>处理建议</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>请求成功。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>输入参数错误。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>3</td>
                  <td>未开通相关权限。</td>
                  <td>请联系 ZEGO 技术支持。</td>
                </tr>
                <tr>
                  <td>4</td>
                  <td>CDN 类型不匹配。</td>
                  <td>请检查参数。</td>
                </tr>
                <tr>
                  <td>5</td>
                  <td>配置错误。</td>
                  <td>请联系 ZEGO 技术支持。</td>
                </tr>
                <tr>
                  <td>6</td>
                  <td>请求过于频繁。</td>
                  <td>请稍后重试。</td>
                </tr>
                <tr>
                  <td>7</td>
                  <td>鉴权失败。</td>
                  <td>请检查鉴权参数是否正确。</td>
                </tr>
                <tr>
                  <td>1000</td>
                  <td>请求失败。</td>
                  <td>请联系 ZEGO 技术支持。</td>
                </tr>
              </tbody>
            </table>
          example: 0
        Message: { type: string , description: 操作结果描述。, example: "success"}
        RequestId: { type: string , description: 请求 ID，由 ZEGO 服务端返回。, example: "4191282558729715911"}
        Data:
          type: object
          description: 响应数据。
          oneOf:
            - type: object
              title: Tencent
              properties:
                Tencent:
                  type: array
                  description: <code>腾讯云</code> 返回内容（Vendor 为 Tencent 时返回）。
                  items:
                    type: object
                    properties:
                      StreamName: { type: string , description: 流名称，即请求参数中的 StreamId。}
                      TaskId: { type: string , description: 任务 ID，全局唯一标识录制任务。}
                      RequestId: { type: string , description: 唯一请求 ID，由请求参数 Vendor 取值对应的 CDN 厂商（即腾讯云）返回，定位问题时需要提供该次请求的 RequestId。}
                      Code: { type: string , description: 当前流的错误码，请参考 Message 信息处理，或联系 ZEGO 技术支持。}
            - type: object
              title: Ws
              properties:
                Ws:
                  type: object
                  description: <code>网宿</code> 返回内容（Vendor 为 Ws 时返回）。
                  properties:
                    msg: { type: object, description: 操作结果提示语。}
                    http_code: { type: integer, format: int32, description: 业务操作状态。}
                    trace_id: { type: string, description: 流水号。}
                    call_time: { type: string, description: 发起请求时间。}
                    list:
                      type: array
                      items:
                        type: object
                        properties:
                          task: { type: string, description: 录制文件的格式。}
                          id: { type: string, description: 流名称，即请求参数中的 StreamId。}
                          http_code: { type: integer, format: int32, description: 该任务的操作状态，请参考 msg 信息处理，或联系 ZEGO 技术支持。}
                          msg: { type: string, description: 该任务的操作结果提示语。}
                          persistentId: { type: string, description: 该任务的文件标识。}
            - type: object
              title: Huawei
              properties:
                Huawei:
                  type: array
                  description: <code>华为云</code> 返回内容（Vendor 为 Huawei 时返回）。
                  items:
                    type: object
                    properties:
                      StreamName: { type: string, description: 流名称，即请求参数中的 StreamId。}
                      RequestId: { type: string, description: 唯一请求 ID，由请求参数 Vendor 取值对应的 CDN 厂商（即 Huawei）返回，定位问题时需要提供该次请求的 RequestId。}
                      Code: { type: integer, format: int32, description: 当前流录制的错误码，请参考 Message 信息处理，或联系 ZEGO 技术支持。}
                      Message: { type: string, description: 当前流录制的错误信息。}
            - type: object
              title: Aliyun
              properties:
                Aliyun:
                  type: array
                  description: <code>阿里云</code> 返回内容（Vendor 为 Aliyun 时返回）。
                  items:
                    type: object
                    properties:
                      StreamName: { type: string, description: 流名称，即请求参数中的 StreamId。}
                      RequestId: { type: string, description: 唯一请求 ID，由请求参数 Vendor 取值对应的 CDN 厂商（即 Aliyun）返回，定位问题时需要提供该次请求的 RequestId。}
                      Code: { type: integer, format: int32, description: 当前流录制的错误码，请参考 Message 信息处理，或联系 ZEGO 技术支持。}
                      Message: { type: string, description: 当前流录制的错误信息。}
          