openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: StopCDNRecord
      description: |
        调用本接口停止 CDN 录制。相关回调请参考[录制文件生成回调](/real-time-video-server/callback/cdn/cdn-record-completed)。

        <Note title="调用频率限制">同一个 AppID 下所有房间：20 次/秒</Note>
      operationId: stop-cdn-record
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=StopCDNRecord
          required: true
          schema: { type: string, enum: [StopCDNRecord] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: StreamId
          in: query
          required: true
          description: 流 ID 列表。<br />以同时停止录制 “cdn01” 和 “cdn02” 两个流为例，请求的参数为：StreamId[]=cdn01和StreamId[]=cdn02。
          schema:
            type: array
            items: { type: string }
            minItems: 1
          style: form
          explode: true
        - name: Vendor
          in: query
          required: true
          schema: { type: string, enum: [Tencent, Ws, Huawei, Aliyun] }
          description: |
            <p>CDN 厂商名。</p>
            <ul>
            <li>Tencent：腾讯云。</li>
            <li>Ws：网宿。</li>
            <li>Huawei：华为云。</li>
            <li>Aliyun：阿里云。</li>
            </ul>
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopCDNRecordResponse'
              examples:
                Tencent:
                  summary: 腾讯云 响应示例（Vendor 为 Tencent 时返回）。
                  value: 
                    Code: 0
                    Message: success
                    RequestId: 4315169065145771656
                    Data:
                      Tencent:
                        - StreamName: cdn01
                          RequestId: d39548da-fbd4-4dce-8023-cfccd28a9963
                          Code: ""
                          Message: ""
                ws:
                  summary: 网宿 响应示例（Vendor 为 Ws 时返回）。
                  value: 
                    Code: 0
                    Message: success
                    RequestId: 16781707661
                    Data:
                      Ws:
                        - task: mp4
                          id: test
                          http_code: 200
                          msg: success
                          persistentId: 202009a378bae528409f87dbe20717415676
                Huawei:
                  summary: 华为云 响应示例（Vendor 为 Huawei 时返回）。
                  value: 
                    Code: 0
                    Message: success
                    RequestId: 16781707661
                    Data:
                      Huawei:
                        - StreamName: hwtest
                          RequestId: f7b1e2f0ca92e7e90f8f0c8b96cds757
                          Code: 0
                          Message: success
                Aliyun:
                  summary: 阿里云 响应示例（Vendor 为 Aliyun 时返回）。
                  value: 
                    Code: 0
                    Message: success
                    RequestId: 16781707661
                    Data:
                      Aliyun:
                        - StreamName: aliyuntest
                          RequestId: 62CBB8E2-2DE1-592C-8842-B00EB2A68A4F
                          Code: 200
                          Message: ""

components:
  schemas:
    StopCDNRecordResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。

            <table>
              <thead>
                <tr>
                  <th>返回码</th>
                  <th>说明</th>
                  <th>处理建议</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>请求成功。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>输入参数错误。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>3</td>
                  <td>未开通相关权限。</td>
                  <td>请联系 ZEGO 技术支持。</td>
                </tr>
                <tr>
                  <td>4</td>
                  <td>CDN 类型不匹配。</td>
                  <td>请检查参数。</td>
                </tr>
                <tr>
                  <td>5</td>
                  <td>配置错误。</td>
                  <td>请联系 ZEGO 技术支持。</td>
                </tr>
                <tr>
                  <td>6</td>
                  <td>请求过于频繁。</td>
                  <td>请稍后重试。</td>
                </tr>
                <tr>
                  <td>7</td>
                  <td>鉴权失败。</td>
                  <td>请检查鉴权参数是否正确。</td>
                </tr>
                <tr>
                  <td>1000</td>
                  <td>请求失败。</td>
                  <td>请联系 ZEGO 技术支持。</td>
                </tr>
              </tbody>
            </table>
          example: 0
        Message: { type: string, description: 操作结果描述。, example: "success" }
        RequestId: { type: string, description: 请求 ID，由 ZEGO 服务端返回。, example: "4315169065145771656" }
        Data:
          type: object
          description: 响应数据。
          oneOf:
            - type: object
              title: Tencent
              properties:
                Tencent:
                  type: array
                  description: <code>腾讯云</code> 返回内容（Vendor 为 Tencent 时返回）。
                  items:
                    type: object
                    properties:
                      StreamName: { type: string, description: 流名称，即请求参数中的 StreamId。, example: "cdn01" }
                      RequestId: { type: string, description: 唯一请求 ID，由请求参数 Vendor 取值对应的 CDN 厂商（即腾讯云）返回，定位问题时需要提供该次请求的 RequestId。, example: "d39548da-fbd4-4dce-8023-cfccd28a9963" }
                      Code: { type: string, description: 当前流的错误码，请参考 Message 信息处理，或联系 ZEGO 技术支持。, example: "" }
                      Message: { type: string, description: 当前流错误信息。, example: "" }
            - type: object
              title: Ws
              properties:
                Ws:
                  type: object
                  description: <code>网宿</code> 返回内容（Vendor 为 Ws 时返回）。
                  properties:
                    msg: { type: object, description: 操作结果提示语。, example: null }
                    http_code: { type: integer, format: int32, description: 业务操作状态。, example: 200 }
                    trace_id: { type: string, description: 流水号。, example: "10021988-6472-4b6d-9f9a-6b5a6d4b6551" }
                    call_time: { type: string, description: 发起请求时间。, example: "2022-05-26 11:46:06" }
                    list:
                      type: array
                      description: 请求任务的处理结果列表。
                      items:
                        type: object
                        properties:
                          task: { type: string, description: 录制文件的格式。, example: "mp4" }
                          id: { type: string, description: 流名称，即请求参数中的 StreamId。, example: "test" }
                          http_code: { type: integer, format: int32, description: 该任务的操作状态，请参考 msg 信息处理，或联系 ZEGO 技术支持。, example: 200 }
                          msg: { type: string, description: 该任务的操作结果提示语。, example: "success" }
                          persistentId: { type: string, description: 该任务的文件标识。, example: "202009a378bae528409f87dbe20717415676" }
            - type: object
              title: Huawei
              properties:
                Huawei:
                  type: array
                  description: <code>华为云</code> 返回内容（Vendor 为 Huawei 时返回）。
                  items:
                    type: object
                    properties:
                      StreamName: { type: string, description: 流名称，即请求参数中的 StreamId。, example: "hwtest" }
                      RequestId: { type: string, description: 唯一请求 ID，由请求参数 Vendor 取值对应的 CDN 厂商（即 Huawei）返回，定位问题时需要提供该次请求的 RequestId。, example: "f7b1e2f0ca92e7e90f8f0c8b96cds757" }
                      Code: { type: integer, format: int32, description: 当前流录制的错误码，请参考 Message 信息处理，或联系 ZEGO 技术支持。, example: 0 }
                      Message: { type: string, description: 当前流录制的错误信息。, example: "success" }
            - type: object
              title: Aliyun
              properties:
                Aliyun:
                  type: array
                  description: <code>阿里云</code> 返回内容（Vendor 为 Aliyun 时返回）。
                  items:
                    type: object
                    properties:
                      StreamName: { type: string, description: 流名称，即请求参数中的 StreamId。, example: "aliyuntest" }
                      RequestId: { type: string, description: 唯一请求 ID，由请求参数 Vendor 取值对应的 CDN 厂商（即 Aliyun）返回，定位问题时需要提供该次请求的 RequestId。, example: "62CBB8E2-2DE1-592C-8842-B00EB2A68A4F" }
                      Code: { type: integer, format: int32, description: 当前流录制的错误码，请参考 Message 信息处理，或联系 ZEGO 技术支持。, example: 200 }
                      Message: { type: string, description: 当前流录制的错误信息。, example: "" }