openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - cloud-recording
        - POST
      summary: DescribeRecordStatus
      description: |
        After starting recording, developers can call this API to query the status of recording tasks. Supports querying tasks whose recording start time is within three days of the API call.

        <Note title="Note">Call frequency limit: 10 times/second</Note>
      operationId: describe-record-status
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://cloudrecord-api.zego.im?Action=DescribeRecordStatus
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DescribeRecordStatus]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRecordStatusRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryRecordStatusResponse'

components:
  schemas:
    QueryRecordStatusRequest:
      type: object
      required: [TaskId]
      properties:
        TaskId:
          type: string
          description: Recording task ID, a fixed-length string of 16 bytes.
          example: "X3CgNeE4I1qAAABN"
      example:
        TaskId: "X3CgNeE4I1qAAABN"

    QueryRecordStatusResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int64
          description: |
            Error code.
          example: 0
        Message:
          type: string
          description: Error description.
          example: "succeed"
        RequestId:
          type: string
          description: Request ID.
          example: "abcd123"
        Data:
          $ref: '#/components/schemas/RecordStatusData'
          description: Response object.
      example:
        Code: 0
        Message: "succeed"
        RequestId: "abcd123"
        Data:
          RoomId: "xxxx"
          RecordMode: 2
          StreamType: 3
          RecordBeginTimestamp: 1601221452099
          RecordEndTimestamp: 1601221508795
          Status: 3
          RecordFiles:
            - UserId: "my_out"
              UserName: "my_out"
              StreamId: "my_out"
              FileId: "X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
              VideoId: "820e50e52e0a490caf44eec8aec527a7"
              FileUrl: "https://xxxx.com/record/X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
              OutputFileFormat: "mp4"
              FileSize: 432643544
              Duration: 33874
              ResolutionWidth: 1920
              ResolutionHeight: 1080
              MediaTrackType: 3
              BeginTimestamp: 1601221459830
              Status: 3

    RecordStatusData:
      type: object
      properties:
        RoomId:
          type: string
          description: Target room for recording.
          example: "xxxx"
        RecordMode:
          type: integer
          description: |
            Recording mode. Please refer to the [Start recording](/cloud-recording-server/start) API.
          example: 2
        StreamType:
          type: integer
          description: |
            Recording media stream type. Please refer to the [Start recording](/cloud-recording-server/start) API.
          example: 3
        RecordBeginTimestamp:
          type: integer
          format: int64
          description: "Recording task start time, Unix timestamp in milliseconds."
          example: 1601221452099
        RecordEndTimestamp:
          type: integer
          format: int64
          description: "Recording task end time, Unix timestamp in milliseconds."
          example: 1601221508795
        Status:
          type: integer
          description: |
            Recording task status.

            - 1: Recording task initialization
            - 2: Recording task in progress
            - 3: Recording task ended
            - 4: Recording task ended abnormally
            - 5: Recording task paused
          enum: [1, 2, 3, 4, 5]
          example: 3
        RecordFiles:
          type: array
          description: |
            File information.

            This field is not returned if the video screenshot feature is used.
            <Warning title="Warning">
            When the recording task is in ended status, if no users published streams in the room during the recording process, no recording files will be generated and the RecordFiles field will not be returned.
            </Warning>
          items:
            $ref: '#/components/schemas/RecordFile'
      example:
        RoomId: "xxxx"
        RecordMode: 2
        StreamType: 3
        RecordBeginTimestamp: 1601221452099
        RecordEndTimestamp: 1601221508795
        Status: 3
        RecordFiles:
          - UserId: "my_out"
            UserName: "my_out"
            StreamId: "my_out"
            FileId: "X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
            VideoId: "820e50e52e0a490caf44eec8aec527a7"
            FileUrl: "https://xxxx.com/record/X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
            OutputFileFormat: "mp4"
            FileSize: 432643544
            Duration: 33874
            ResolutionWidth: 1920
            ResolutionHeight: 1080
            MediaTrackType: 3
            BeginTimestamp: 1601221459830
            Status: 3

    RecordFile:
      type: object
      properties:
        UserId:
          type: string
          description: User ID of the stream being recorded (for stream mixing, this is MixOutputStreamId).
          example: "my_out"
        UserName:
          type: string
          description: User nickname of the stream being recorded (for stream mixing, this is MixOutputStreamId).
          example: "my_out"
        StreamId:
          type: string
          description: Stream ID of the stream being recorded (for stream mixing, this is MixOutputStreamId).
          example: "my_out"
        FileId:
          type: string
          description: |
            File ID. Please refer to the OutputFileRule parameter in the [Start recording](/cloud-recording-server/start) API.
          example: "X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
        VideoId:
          type: string
          description: Video ID parameter obtained after successful upload to Alibaba Cloud VOD or Tencent Cloud VOD. For Alibaba Cloud VOD, this corresponds to VideoId; for Tencent Cloud VOD, this corresponds to FileId.
          example: "820e50e52e0a490caf44eec8aec527a7"
        FileUrl:
          type: string
          description: File access URL. Not returned when third-party storage is Qiniu Cloud or Alibaba Cloud VOD.
          example: "https://xxxx.com/record/X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
        OutputFileFormat:
          type: string
          description: |
            Output recording file format, including "mp4", "flv", "hls", "jpg", and "aac".
          enum: ["mp4", "flv", "hls", "jpg", "aac"]
          example: "mp4"
        FileSize:
          type: integer
          format: int64
          description: "File size in bytes."
          example: 432643544
        Duration:
          type: integer
          description: "File duration in milliseconds."
          example: 33874
        ResolutionWidth:
          type: integer
          description: "Video resolution width in pixels."
          example: 1920
        ResolutionHeight:
          type: integer
          description: "Video resolution height in pixels."
          example: 1080
        MediaTrackType:
          type: integer
          description: |
            File media type.

            - 1: Audio only
            - 2: Video only
            - 3: Audio and video
          enum: [1, 2, 3]
          example: 3
        BeginTimestamp:
          type: integer
          format: int64
          description: "Unix timestamp when file recording started, in milliseconds."
          example: 1601221459830
        Status:
          type: integer
          description: |
            File status.

            - 1: Recording, indicates the file is being recorded.
            - 2: Uploading, indicates the recording file is being uploaded to the customer-specified cloud storage.
            - 3: Upload successful, indicates the recording file has been successfully uploaded to the customer-specified cloud storage.
            - 4: Uploaded to backup cloud storage, indicates upload to customer-specified cloud storage failed and has been uploaded to ZEGOCLOUD backup cloud storage. **Please note that ZEGOCLOUD backup cloud storage is valid for 3 days. Please download the recording file promptly and save it locally.**
            - 5: Upload failed, indicates upload to both customer-specified cloud storage and ZEGOCLOUD backup cloud storage failed.
          enum: [1, 2, 3, 4, 5]
          example: 3
      example:
        UserId: "my_out"
        UserName: "my_out"
        StreamId: "my_out"
        FileId: "X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
        VideoId: "820e50e52e0a490caf44eec8aec527a7"
        OutputFileFormat: "mp4"
        FileSize: 432643544
        Duration: 33874
        ResolutionWidth: 1920
        ResolutionHeight: 1080
        MediaTrackType: 3
        BeginTimestamp: 1601221459830
        Status: 3
        FileUrl: "https://xxxx.com/record/X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"

