openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - messaging

paths:
  /:
    post:
      tags: [messaging]
      summary: Send group messages
      description: |
        Send group messages and push them to all online users in the group.

        The client will receive group message notifications through the ZIM SDK callback interface.
        <Note title="Note">After enabling the content moderation feature, messages sent by the server will be moderated by default. If messages sent by the server do not need to be moderated, please contact ZEGOCLOUD Technical Support for configuration.</Note>

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|-------|---------|
        | [groupMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-group-message-received-info-from-group-id) | [onGroupMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-group-message-received) | [groupMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-group-message-received-info-from-group-id) | [onGroupMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-group-message-received) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |---------|---------|---------|---------|
        | [groupMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#group-message-received) | [groupMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#group-message-received) | [onGroupMessageReceived](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onGroupMessageReceived.html) | [groupMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#group-message-received) |

        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|---------|
        | [onReceiveGroupMessage](https://www.zegocloud.com/docs/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-receive-group-message) | [groupMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#group-message-received) | [groupMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#group-message-received) |  |

        <Note title="Note">
        The parameters FromUserId and GroupId only support numbers, English characters, and `'!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'{'，'}'，'|'，'~'`.
        </Note>

        <Note title="Note">
        If the sender's SDK version (for version information, please refer to [Release notes](/zim-android/client-sdks/zim-release-notes)) is lower than 2.0.0, the ZIM server only supports Command type messages with `MessageType` of `2`, and does not support other types.<br/>To provide developers with a better experience, ZEGOCLOUD recommends that developers use the latest version of the SDK.

        If the sender requests to send a text message with MessageType 1, the sender's corresponding client (SDK version needs to be 2.7.0 or above) will also receive the message.

        For sending and receiving custom messages with MessageType 200, the SDK version of the sender's and receiver's corresponding clients needs to be 2.8.0 or above.

        If the receiver's SDK version is in the [2.0.0, 2.8.0) range, they can receive custom messages, but the message type will be displayed as unknown and the message content cannot be obtained. To obtain this message, please upgrade the SDK to version 2.8.0 or above.

        If the receiver's SDK version is 1.x.x, they will not be able to receive custom messages, nor will they receive unknown messages.
        </Note>
        <Note title="QPS Limit"> 10 times/s</Note>
      operationId: send-group-messages
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=SendGroupMessage
          required: true
          schema:
            type: string
            enum: [SendGroupMessage]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendGroupMessageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendGroupMessageResponse'

components:
  schemas:
    SendGroupMessageRequest:
      type: object
      required: [FromUserId, GroupId, MessageType, Priority, MessageBody]
      properties:
        FromUserId:
          type: string
          description: Sender's user ID (who has logged in to the ZIM service by calling the login method on the client, or has completed registration by calling the [server-side API](/zim-server/user/batch-register-users)).
          maxLength: 32
          example: "u1"
        GroupId:
          type: string
          description: Group ID.
          maxLength: 32
          example: "r1"
        MessageType:
          type: number
          format: int32
          description: Message type. For applicable types for group conversations, please refer to [MessageBody](/zim-server/messaging/messagebody-introduction) description.
          example: 1
        Priority:
          type: number
          format: int32
          description: |
            Message priority (for details, please refer to [Basic concepts - Message priority](/zim-android/introduction/basic-concepts#message-priority)). Values are as follows:
              - 1: Low.
              - 2: Medium.
              - 3: High.
          enum: [1, 2, 3]
          example: 1
        MessageBody:
          type: object
          description: Message content. For specific parameter format, please refer to [MessageBody](/zim-server/messaging/messagebody-introduction) description.
          example:
            Message: "hello world"
            ExtendedData: "d"
            OfflinePush:
              Enable: 0
              Title: "Title"
              Content: "Content"
              Payload: "data"
        SubMsgType:
          type: number
          description: Specific custom type. The value is defined by the developer, with a value range of [0,200]. This parameter only needs to be assigned when MessageType is a custom message.
        SearchedContent:
          type: string
          description: Search field for custom messages. This field can only be filled in when MessageType is a custom message, with a default maximum length of 64 bytes. This field applies to the client. Unless this field is filled in, the associated custom message cannot be searched through the client.
        SendMsgOptions:
          type: object
          description: Optional configuration items.
          example:
            NoUnread: true
            TargetOption:
              Inclusive: true
              ReceiverUserIds: ["userA", "userB"]
          properties:
            NoUnread:
              type: boolean
              description: |
                Whether this message will increase the receiver's unread message count.
                - false: (Default) Yes.
                - true: No.
              example: true
            TargetOption:
              type: object
              description: |
                Configuration items for group targeted messages.

                > Note
                >
                > If the TargetOption parameter is configured, this message will not be counted in the unread count regardless of whether NoUnread is set to false or true.
              example:
                Inclusive: true
                ReceiverUserIds: ["userA", "userB"]
              properties:
                ReceiverUserIds:
                  type: array
                  description: User ID list.
                  items:
                    type: string
                  example: ["userA", "userB"]
                Inclusive:
                  type: boolean
                  description: |
                    Target type.
                    - false: (Default) Reverse targeting, i.e., users listed in ReceiverUserIds will not receive this message.
                    - true: Forward targeting, i.e., only users listed in ReceiverUserIds will receive this message.
                  example: true
    SendGroupMessageResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <tbody><tr>
            <th>Return code</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000025</td>
            <td>After passing 1 for IsBase64 in MessageBody, sending base64-encoded signaling messages failed.</td>
            <td>
            Please confirm:
            <ul>
            <li>Please confirm whether IsBase64 needs to be 1, i.e., whether binary type signaling messages need to be sent.</li>
            <li>Please confirm whether the message content is base64 encoded.</li>
            </ul>
            </td>
            </tr>
            <tr>
            <td>660400001</td>
            <td>The input message size exceeds the limit.</td>
            <td>Please check the input message size.</td>
            </tr>
            <tr>
            <td>660500002</td>
            <td>Message sender has not logged in to the SDK.</td>
            <td>Please have the user log in first before sending messages.</td>
            </tr>
            <tr>
            <td>660600001</td>
            <td>The input GroupId does not exist.</td>
            <td>Please confirm if the input GroupId is correct.</td>
            </tr>
            </tbody></table>
        Message:
          type: string
          description: Description of the request result.
        RequestId:
          type: string
          description: Request ID.
        MsgSeq:
          type: number
          description: Message Seq. When the message type is a signaling message, this field is empty. Can be used for [Recall a group message](/zim-server/messaging/recall-a-group-message).
        MsgId:
          type: number
          description: Message ID.
        AuditInfos:
          type: array
          description: Audit structure array. When the array is not empty, it indicates that there are messages that failed the audit, and you can view the reason for the audit failure through this structure.
          items:
            type: object
            properties:
              Index:
                type: number
                description: |
                  This parameter may have the following situations:
                  - When you have enabled the ZIM content moderation service and have not rejected the message through the [message not sent yet callback](/zim-server/callbacks/message-not-sent-yet):
                    - For combined messages, this parameter indicates the index of the Item that failed the audit in the combined message, starting from 0.
                    - For other types of messages, this parameter is always 0.
                  - When you reject this message after receiving the message not sent yet callback, this parameter is always 0 regardless of the message type.
              Reason:
                type: string
                description: Rejection reason.
      description: |
        For return code examples, see the "Return codes" section of the documentation.
      example:
        Code: 0
        Message: "success"
        RequestId: "343649807833778782"
        MsgSeq: 1
        MsgId: 1
        AuditInfos:
          - Index: 0
            Reason: "reason"    # Return the reason for audit failure
