openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - cloud-recording
        - POST
      summary: DescribeRecordStatus
      description: |
        开始录制后，开发者可以通过调用本接口来查询录制任务的状态。支持查询录制开始时间在发起接口调用时三天内的任务。

        <Note title="说明">调用频率限制：10 次/秒</Note>
      operationId: describe-record-status
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://cloudrecord-api.zego.im?Action=DescribeRecordStatus
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DescribeRecordStatus]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRecordStatusRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryRecordStatusResponse'

components:
  schemas:
    QueryRecordStatusRequest:
      type: object
      required: [TaskId]
      properties:
        TaskId:
          type: string
          description: 录制任务 ID，长度固定为 16 个字节的字符串。
          example: "X3CgNeE4I1qAAABN"
      example:
        TaskId: "X3CgNeE4I1qAAABN"

    QueryRecordStatusResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int64
          description: |
            错误码。
          example: 0
        Message:
          type: string
          description: 错误描述。
          example: "succeed"
        RequestId:
          type: string
          description: 请求 ID。
          example: "abcd123"
        Data:
          $ref: '#/components/schemas/RecordStatusData'
          description: 响应对象。
      example:
        Code: 0
        Message: "succeed"
        RequestId: "abcd123"
        Data:
          RoomId: "xxxx"
          RecordMode: 2
          StreamType: 3
          RecordBeginTimestamp: 1601221452099
          RecordEndTimestamp: 1601221508795
          Status: 3
          RecordFiles:
            - UserId: "my_out"
              UserName: "my_out"
              StreamId: "my_out"
              FileId: "X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
              VideoId: "820e50e52e0a490caf44eec8aec527a7"
              FileUrl: "https://xxxx.com/record/X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
              OutputFileFormat: "mp4"
              FileSize: 432643544
              Duration: 33874
              ResolutionWidth: 1920
              ResolutionHeight: 1080
              MediaTrackType: 3
              BeginTimestamp: 1601221459830
              Status: 3

    RecordStatusData:
      type: object
      properties:
        RoomId:
          type: string
          description: 录制的目标房间。
          example: "xxxx"
        RecordMode:
          type: integer
          description: |
            录制模式。请参考 [开始录制](/cloud-recording-server/start-record) 接口。
          example: 2
        StreamType:
          type: integer
          description: |
            录制媒体流类型。请参考 [开始录制](/cloud-recording-server/start-record) 接口。
          example: 3
        RecordBeginTimestamp:
          type: integer
          format: int64
          description: 录制任务开始的时间，为 Unix 时间戳，单位：ms。
          example: 1601221452099
        RecordEndTimestamp:
          type: integer
          format: int64
          description: 录制任务结束的时间，为 Unix 时间戳，单位：ms。
          example: 1601221508795
        Status:
          type: integer
          description: |
            录制任务的状态。

            - 1：录制任务初始化
            - 2：录制任务进行中
            - 3：录制任务已结束
            - 4：录制任务异常结束
            - 5：录制任务暂停中
          enum: [1, 2, 3, 4, 5]
          example: 3
        RecordFiles:
          type: array
          description: |
            文件信息。

            如果使用了视频截图功能，则不返回该字段。
            <Warning title="注意">
            录制任务为已结束状态时，如果录制过程中房间内无用户推流，则不会产生录制文件，也不会返回 RecordFiles 字段。
            </Warning>
          items:
            $ref: '#/components/schemas/RecordFile'
      example:
        RoomId: "xxxx"
        RecordMode: 2
        StreamType: 3
        RecordBeginTimestamp: 1601221452099
        RecordEndTimestamp: 1601221508795
        Status: 3
        RecordFiles:
          - UserId: "my_out"
            UserName: "my_out"
            StreamId: "my_out"
            FileId: "X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
            VideoId: "820e50e52e0a490caf44eec8aec527a7"
            FileUrl: "https://xxxx.com/record/X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
            OutputFileFormat: "mp4"
            FileSize: 432643544
            Duration: 33874
            ResolutionWidth: 1920
            ResolutionHeight: 1080
            MediaTrackType: 3
            BeginTimestamp: 1601221459830
            Status: 3

    RecordFile:
      type: object
      properties:
        UserId:
          type: string
          description: 录制流对应的推流用户 ID（混流时，为 MixOutputStreamId）。
          example: "my_out"
        UserName:
          type: string
          description: 录制流对应的推流用户昵称（混流时，为 MixOutputStreamId）。
          example: "my_out"
        StreamId:
          type: string
          description: 录制流对应的流 ID（混流时，为 MixOutputStreamId）。
          example: "my_out"
        FileId:
          type: string
          description: |
            文件 ID，请参考 [开始录制](/cloud-recording-server/start-record) 接口中的 OutputFileRule 参数。
          example: "X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
        VideoId:
          type: string
          description: 阿里云 Vod、腾讯云 Vod 上传成功得到的视频 ID 参数。阿里云 Vod 对应的是 VideoId，腾讯云 Vod 对应的是 FileId。
          example: "820e50e52e0a490caf44eec8aec527a7"
        FileUrl:
          type: string
          description: 文件访问 URL。第三方存储为七牛云或阿里云 Vod 时不返回。
          example: "https://xxxx.com/record/X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
        OutputFileFormat:
          type: string
          description: |
            输出录制文件的格式，包括 "mp4"、"flv"、"hls"、"jpg" 和 "aac"。
          enum: ["mp4", "flv", "hls", "jpg", "aac"]
          example: "mp4"
        FileSize:
          type: integer
          format: int64
          description: 文件大小，单位：字节。
          example: 432643544
        Duration:
          type: integer
          description: 文件时长，单位：ms。
          example: 33874
        ResolutionWidth:
          type: integer
          description: 视频分辨率宽，单位：像素。
          example: 1920
        ResolutionHeight:
          type: integer
          description: 视频分辨率高，单位：像素。
          example: 1080
        MediaTrackType:
          type: integer
          description: |
            文件媒体类型。

            - 1：只有音频
            - 2：只有视频
            - 3：音视频
          enum: [1, 2, 3]
          example: 3
        BeginTimestamp:
          type: integer
          format: int64
          description: 开始录制文件时的 Unix 时间戳，单位：ms。
          example: 1601221459830
        Status:
          type: integer
          description: |
            文件状态。

            - 1：录制中，表示正在录制文件。
            - 2：上传中，表示正在上传录制文件至客户指定云存储。
            - 3：上传成功，表示上传录制文件至客户指定云存储成功。
            - 4：已经上传至备份云存储，表示上传客户指定云存储失败，已上传至 ZEGO 备份云存储。**请注意，ZEGO 备份云存储的有效期为 3 天，请您及时下载录制文件，保存到本地。**
            - 5：上传失败，表示上传客户指定云存储和 ZEGO 备份云存储均失败。
          enum: [1, 2, 3, 4, 5]
          example: 3
      example:
        UserId: "my_out"
        UserName: "my_out"
        StreamId: "my_out"
        FileId: "X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"
        VideoId: "820e50e52e0a490caf44eec8aec527a7"
        OutputFileFormat: "mp4"
        FileSize: 432643544
        Duration: 33874
        ResolutionWidth: 1920
        ResolutionHeight: 1080
        MediaTrackType: 3
        BeginTimestamp: 1601221459830
        Status: 3
        FileUrl: "https://xxxx.com/record/X3CgNeE4I1qAAABN_xxxx_my_out_VA_20200927154419775.mp4"

