openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - cloud-recording
        - POST
      summary: DescribeTasks
      description: |
        开始录制后，开发者可以通过调用本接口，查询正在录制或已结束录制的任务列表。

        <Note title="说明">调用频率限制：10 次/秒</Note>
      operationId: describe-tasks
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://cloudrecord-api.zego.im?Action=DescribeTasks
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DescribeTasks]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRecordTaskListRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryRecordTaskListResponse'

components:
  schemas:
    QueryRecordTaskListRequest:
      type: object
      required: [Status, StartTime, EndTime]
      properties:
        Status:
          type: integer
          description: |
            录制任务状态。

            - 2：表示正在录制的任务。
            - 3：表示已结束录制的任务。
          enum: [2, 3]
          example: 2
        RoomId:
          type: string
          description: 用于指定要查询录制任务的房间号。不填写时查询 AppId 下所有房间的录制任务。
          example: "1230"
        PageOffset:
          type: integer
          description: 分页查询时的页码，从 1 开始。不填写或者填写为 0 时，默认为 1。
          default: 1
          minimum: 1
          example: 1
        PageSize:
          type: integer
          description: 分页查询时每页的记录条数，该值需小于等于 50，并且大于 0。不填写时默认为 50。
          default: 50
          minimum: 1
          maximum: 50
          example: 50
        StartTime:
          type: integer
          format: int64
          description: 查询的开始时间，为Unix 时间戳，单位：ms。开始时间不能早于当前时间的 3 天之前。
          example: 1628474401000
        EndTime:
          type: integer
          format: int64
          description: 查询的结束时间，为Unix 时间戳，单位：ms。EndTime 必须大于 StartTime，且查询时间跨度不超过 3 天。接口仅返回录制开始时间在查询时间范围内的记录。
          example: 1628475402000
      example:
        Status: 2
        RoomId: "1230"
        StartTime: 1628474401000
        EndTime: 1628475402000
        PageOffset: 1
        PageSize: 50

    QueryRecordTaskListResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int64
          description: |
            错误码。
          example: 0
        Message:
          type: string
          description: 错误描述。
          example: "succeed"
        RequestId:
          type: string
          description: 请求 ID。
          example: "abcd123"
        Data:
          $ref: '#/components/schemas/RecordTaskListData'
          description: 响应对象。
      example:
        Code: 0
        Message: "succeed"
        RequestId: "abcd123"
        Data:
          PageOffset: 1
          PageSize: 50
          TotalCount: 3
          TaskidList:
            - RecordBeginTimestamp: 1628565227899
              TaskId: "YRHu6-E4IyvEAAAD"
              RoomId: "1000"
              Status: 2
            - RecordBeginTimestamp: 1628565226303
              TaskId: "YRHu6uE4IyvEAAAC"
              RoomId: "1000"
              Status: 2
            - RecordBeginTimestamp: 1628565222498
              TaskId: "YRHu5uE4IyvEAAAB"
              RoomId: "1000"
              Status: 2

    RecordTaskListData:
      type: object
      properties:
        PageOffset:
          type: integer
          description: 分页查询时的页码。
          example: 1
        PageSize:
          type: integer
          description: 分页查询时每页的记录条数。
          example: 50
        TotalCount:
          type: integer
          description: 查询结果总数。
          example: 3
        TaskidList:
          type: array
          description: |
            录制任务列表。
          items:
            $ref: '#/components/schemas/RecordTaskItem'
      example:
        PageOffset: 1
        PageSize: 50
        TotalCount: 3
        TaskidList:
          - RecordBeginTimestamp: 1628565227899
            TaskId: "YRHu6-E4IyvEAAAD"
            RoomId: "1000"
            Status: 2
          - RecordBeginTimestamp: 1628565226303
            TaskId: "YRHu6uE4IyvEAAAC"
            RoomId: "1000"
            Status: 2
          - RecordBeginTimestamp: 1628565222498
            TaskId: "YRHu5uE4IyvEAAAB"
            RoomId: "1000"
            Status: 2

    RecordTaskItem:
      type: object
      properties:
        RecordBeginTimestamp:
          type: integer
          format: int64
          description: 开始录制的时间戳，单位：ms。
          example: 1628565227899
        TaskId:
          type: string
          description: 录制任务 ID。
          example: "YRHu6-E4IyvEAAAD"
        RoomId:
          type: string
          description: 录制的目标房间 ID。
          example: "1000"
        Status:
          type: integer
          description: |
            录制状态。

            - 1：录制任务初始化
            - 2：录制任务进行中
            - 3：录制任务已结束
            - 4：录制任务异常结束
            - 5：录制任务暂停中
          enum: [1, 2, 3, 4, 5]
          example: 2
      example:
        RecordBeginTimestamp: 1628565227899
        TaskId: "YRHu6-E4IyvEAAAD"
        RoomId: "1000"
        Status: 2

